adotefga/config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  resources :comments
  root to: redirect('/posts')
  devise_for :users
  resources :events
  
  resources :posts
  resources :ideas, only: [:show, :index, :new]
  resources :events, only: [:show, :create, :new, :index]

end

adotefga/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

adotefga/app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
end

adotefga/app/models/event.rb
class Event < ActiveRecord::Base
    mount_uploader :picture, PictureUploader
end

adotefga/app/models/event_registration.rb
class EventRegistration < ActiveRecord::Base
    belongs_to :event
    belongs_to :user
end

adotefga/app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    mount_uploader :picture, PictureUploader
  
            
end

adotefga/app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic
   
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

adotefga/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

adotefga/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :post_id)
    end
end

adotefga/app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
    before_action :authenticate_user!, except: [:index]

  private

    def event_params
      params.require(:event).permit(:title, :description, :picture, :start_date, :end_date)
    end
end

adotefga/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /posts
  # GET /posts.json
  def index
    if params[:search]
     @posts = Post.where("name like?", "%#{params[:search]}%")
    else
        @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.all
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :description, :picture)
    end
end

adotefga/app/helpers/application_helper.rb
module ApplicationHelper
end

adotefga/app/helpers/comments_helper.rb
module CommentsHelper
end

adotefga/app/helpers/events_helper.rb
module EventsHelper
end

adotefga/app/helpers/posts_helper.rb
module PostsHelper
end

adotefga/app/helpers/welcome_helper.rb
module WelcomeHelper
end

adotefga/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, id: :comment_body %>
  </div>
  <%= f.hidden_field :post_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

adotefga/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

adotefga/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

adotefga/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

adotefga/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

adotefga/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

adotefga/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

adotefga/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron text-center" >
<h1>Eventos</h1>

<% @events.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |event| %>
      <div class="col-md-4">
    
        <%= image_tag event.picture_url, width: '100%' if event.picture.present? %>
        <h4><%= link_to event.title, event %></h4>
      </div>
    <% end %>
  </div>
<% end %>
</div>

adotefga/app/views/events/new.html.erb
<div class="jumbotron text-center" >

<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>
</div>

adotefga/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@event.picture_url, width: 600) if @event.picture.present? %>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

adotefga/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = "pt-br">
<head>
 <meta charset = "utf-8"/>
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <title>Adotefga</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar navbar-light", style="background-color: #4B0082;">
  <div class="container">
  <div class "navbar-header">
  <a class="navbar-brand pull-right"><a class="navbar-brand" href="#">
  <img src="https://t4.ftcdn.net/jpg/02/10/08/03/500_F_210080316_PkgWpFfNOg7aoTo6lRnwk2vb9JuZMjdb.jpg" width="120" height="120" >
</a>

    <a class="navbar-brand nav-link" href="/">Adote FGA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/posts">Posts</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/events">Eventos</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Novo Post', new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Novo Evento', new_event_path, class: "nav-link" %>
        </li>
      </ul>
      <li class="nav-item">
        <div id="calendar"></div>
      </li>
     
  <form class="form-inline">
    <%= form_tag(posts_path, :method => :get) do %>
        <input class = "form-control mr-sm-2" <%= text_field_tag 'search', nil, placeholder: 'pesquisar' %>
        
        <%= submit_tag 'pesquisar', :class => "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
  </form>

    </div>
    </ul>
  </div>
  <ul class="navbar-nav mr-auto">

    <li class="nav-item">
         <% if user_signed_in? %><p><%= image_tag current_user.gravatar_url, :class => "gravatar" %><a class="nav-link text-white" rel="nofollow" data-method="DELETE" href="/users/sign_out">Sair</a></p>
         <%else%><a class="nav-link text-white" href="/users/sign_in">Entrar</a>
           <%end %>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <%= yield %>
  
</div>
<footer>
  <div class="container">
    Universidade de Brasília - Campus Gama <%= Time.now.year %>
  </div>
</footer>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

</body>
</html>

adotefga/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
     <%= f.text_field :name %>
    
  </div>
  <div class="field">
    
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

    
   
    
    

adotefga/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

    

adotefga/app/views/posts/index.html.erb
<div class="jumbotron text-center" >
 <h1>Animais que precisam de um lar</h1>
 
<% @posts.in_groups_of(3) do |group| %>
  
      <div class="row">
        <% group.compact.each do |post| %>
            <div class="col-md-4">

             <h4><%= link_to post.name, post %></h4>
            <%= image_tag post.picture_url, width: '100%' if post.picture.present? %>
        
      </div>
      
        <% end %>
    </div>
  
  <% end %>
</div>

adotefga/app/views/posts/new.html.erb
<div class="container-fluid jumbotron text-center" >
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

adotefga/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center" >
<div class="row">
  <div class="col-md-9">
  
    <%= image_tag(@post.picture_url, width: '50%') if @post.picture.present? %>
    <h3>Comments</h3>
    <% @comments.each do |comment| %>
      <div>
        <strong><%= comment.user_name %></strong>
        <br>
        <p><%= comment.body %></p>
        
        <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
        
      </div>
    <% end %>
    <%= render partial: 'comments/form', locals: { comment: @comment } %>
    
  </div>

  <div class="col-md-3">
    <p><b>Name: </b><%= @post.name %></p>
    <p><b>Description: </b><%= @post.description %></p>
    <p><%= link_to 'Back', posts_path %></p>
  </div>
  </div>

adotefga/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

adotefga/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>